name: anirbanchatterjee
favicon: null
layout_spectrum: 0.7531
typography_spectrum: 0.7643584520556033
title: anirban chatterjee photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fdfdfd'
    - '#53504c'
    - '#a8a7ae'
    - '#807c7a'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
